### ISSUE TITLE
Find a better organization for notebooks

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-events#5]
@adrienpacifico @cbenz @eraviart 

Suite aux discussions pendant le hackathon, je me suis lancé sur les notebooks. 
J'ai commencé à nettoyer les notebooks (ceux dans users/benjello). Le but est de ne garder que les notebooks propres, de pouvoir les tester et de les migrer vers les bons repos pour réduire le nombre de repos à mettre à jour (changement de nom de variables etc).  

Pour que l'on soit efficace, il me semble qu'il faut mettre une section notebook dans openfisca-france avec quelques exemples et les tester (et mettre des noms meaningful). La question qui se pose est ou mettons-nous les notebooks avec un appel API ? Il y a peut-être également d'autres points de la documentation qui font référence à des notebooks n'hésitez pas à les mentionner pour que l'on leur trouve une place adéquate.

Next steps (que les pressentis créent les issues kivonbien, ou râlent ;-) ):
- que fait-on des notebooks API (@cbenz / @eraviart ) ?
- tester que les notebooks tournent/donnent les mêmes résultats dans travis (@cbenz / @eraviart )
- préparer un pas-à-pas pédagogique pour opefisca-france (@adrienpacifico / @benjello) à partir des notebooks qui se trouvent [ici](https://github.com/openfisca/openfisca-web-notebook/tree/335256942c388d23129e926e2358736d9d053c1c/users/benjello)

Comments very welcome.

**Comment by benjello** [comment]
Again comments welcome as cleaners ;-)
@cbenz : do we have a way of testing that the notebooks do run ?
@edarin and @adrienpacifico do you have apetite for the last point ?

**Comment by edarin** [comment]
For sure !
I have already begun

**Comment by adrienpacifico** [comment]
@benjello oui, que fait @edarin, stagiaire IPP ?
 
J'avais fait un notebook sur les périodes qui a besoin d'un petit peu de polish (pas fini).
@cbenz avait passé du temps pour l'améliorer mais j'ai perdu les modifs (plusieurs onglets ouverts sous jupyter-hub, j'ai écrasé ce qu'il a fait par erreur), mes excuses...
Je viens de faire une PR, à vous de voir s'il a un intérêt et de l'améliorer si besoin.

Je suis totalement sous l'eau niveau travail, je suivrai les notebook qui sont lancés et contribuerai peut être si je peux aider. Mais à court terme je ne vais pas créer de nouveaux notebooks.

**Comment by benjello** [comment]
@edarin est à Etalab !
Et elle est très efficace

**Comment by edarin** [comment]
I just wanted to add that we have decided with cbenz to have the pedagocial notebooks in this repository : https://github.com/openfisca/openfisca-france/tree/master/notebooks

With pedagocgical notebooks I mean the ones which are dedicated to other users to learn how to use OpenFisca.

**Comment by adrienpacifico** [comment]
Wouldn't it be better to have documentation (pedagogical or technical) separated from openfisca-france ? Maybe by creating a pedagogical repo here ?

**Comment by edarin** [comment]
I don't have a special mind about it 
-> @cbenz might have one ?

**Comment by benjello** [comment]
I think that the notebook linked to the documentation should stay in openfisca-france and automatically tested. 
More thematic notebooks could be hosted elsewhere for the moment.
Let's have few clean and well organised tested notebooks and then we will move on to a more ambitious goals.

**Comment by cbenz** [comment]
So, my views...

> que fait-on des notebooks API (@cbenz / @eraviart ) ?

Notebooks showing usages of the web API should be dropped. This is not their role, as the main target language for web API is JavaScript and no-one will be interested into calling the web API from Python, since they can call OpenFisca directly.

> tester que les notebooks tournent/donnent les mêmes résultats dans travis (@cbenz / @eraviart )

I started to select some software for running notebooks but didn't have the time to choose one neither a methodology. This is a WIP.

> préparer un pas-à-pas pédagogique pour opefisca-france (@adrienpacifico / @benjello) à partir des notebooks qui se trouvent ici

This should be the "getting started" notebook @edarin talked about.

> Wouldn't it be better to have documentation (pedagogical or technical) separated from openfisca-france ? 

I really think that economists are going to install `OpenFisca-France` and `jupyter` on their machine. We try to make them avoid any `git clone`. So if there's a `openfisca notebook` command (as we already have `openfisca serve` for the Web API) which *just* launches `jupyer notebook` in the right directory (`openfisca-france/notebooks`) this would be great.

**Comment by adrienpacifico** [comment]
Good with @cbenz views, but then what is the purpose of this repo, only events (hackathon) and specific usage of OpenFisca (policy briefs, etc).

**Comment by benjello** [comment]
@adrienpacifico : let's find a proper way to handle notebooks and then we will be more specific about this repo. For the moments it is just a centralized collection of various notebooks.

**Comment by edarin** [comment]
I'm not sure that I get all the details. Should I move the getting-started notebook which is in openfisca/openfisca-france/notebooks to openfisca/openfisca-web-notebook ? If not should I bring back the notebook "period" of adrienpacifico in the first one ?

**Comment by benjello** [comment]
The second solution is better. And I would rework @adrienpacifico notebook to be more didactic.
Start with explaining the period class. Then how to set it in a simulation as a scenario parameters then as a calculate argument. Then calculate_add etc. With sound examples (irrp, af and may be some cotisations sociales are good examples). And try to always explicit keyword arguments than positional argument.  

We could also start to list some FAQs ...

**Comment by adrienpacifico** [comment]
Well, I think the needs for practical usage exemples are higher than rigourous exemples (with descriptives exemple of classes, etc), at least for economist. Being able to run the software in a correct way with small cognitive cost, is more likely to attract users than learning the hard way what is the period class and all (which most end-users will note care except for very specific applications). Positional argument is the way most formulas are written and the way most end-users will use it...

This is just my feelings as an end-user : I prefer to have working results without knowing how it works than the opposite. Up to me to spend more time trying to understand subtleties in internals (which is usually don't want to :-) ). I might be wrong about it...

**Comment by sandcha** [comment]
As this was some time ago, @benjello @adrienpacifico @cbenz which notebooks would you advise to keep?

**Comment by Morendil** [comment]
Il me semble qu'on a trouvé ce qu'on cherchait avec tutorial, je ferme.
